### ISSUE TITLE
setting `disable_overscan` has no effect on my system

### ISSUE THREAD

**Issue by AGS-Knight** [ukscone/set_overscan#2]
This program was really helpful - thanks for putting it together.  I had trouble in that no matter how I set `disable_overscan` in `/boot/config.txt` and rebooted, I would get the same error message :

> "Overscan is currently disabled. Please add the line disable_overscan to the bottom of the config.txt"

I tried:

* `disable_overscan=0`
* `disable_overscan=1`
* `disable_overscan`
* `#disable_overscan=0`
* `#disable_overscan=1`
* `#disable_overscan`

When I ran `vcgencmd get_config int`, I would see `disable_overscan=1` regardless of the settings I had in  `/boot/config.txt`.  

Anyway, commenting out the block of code in `set_overscan.sh` that tests for overscan (`` if [ `vcgencmd get_config disable_overscan | awk -F '=' '{print $2}'` -eq "1"``) allowed the program to run perfectly.

**Comment by ukscone** [comment]
i've just tried it again on a fresh sd card and it seems fine here and checking manually gives what i expect but i'll have a fiddle and see if i can replicate your observation and if yes i'll try to fix

**Comment by ymost** [comment]
I got the exact same behavior as @AGS-Knight, in case it helps

**Comment by ukscone** [comment]
it looks like a few assumptions i made at the beginning are now false as the raspberry pi firmware has changed over the years. i've had a little fiddle around and used some of the changes that Alex Bradbury made to his version of set_overscan so give the new version a go and see if that helps
