### ISSUE TITLE
Only half of screen is filled with random data

### ISSUE THREAD

**Issue by micw** [ukscone/set_overscan#5]
Great helpfull tool, thank you!

on my Raspberry, only the upper half of the screen is filled with random data which makes it hard to set the lower right corner.

**Comment by ukscone** [comment]
hi

sorry for the delay in getting back to you but I was off-grid for a few days.

can you run

TEMP=$(fbset | grep 'mode "' | awk -F ' ' '{print $2}' | tr \" \ )

echo $TEMP

and see if that matches your screen resolution and let me know please

**Comment by axlroden** [comment]
happens to me too, but shouldn't matter it fills out the lower half when that is needing adjustment.

**Comment by ukscone** [comment]
i've not been able to reproduce yet but will keep trying.

can you try

TEMP=$(fbset | grep 'mode "' | awk -F ' ' '{print $2}' | tr \" \ )

echo $TEMP

and post the result please

**Comment by jtkeyva** [comment]
Happens to me too. Just the top half fills with colored pixels. I put in that command and here is my result:
1280x720

Thanks

**Comment by ukscone** [comment]
ok thanks. that is what I expected and nice to have it confirmed. i think i might know what the problem is but I won't be able to confirm until the weekend. once i have confirmed if that is the problem I should have a fix soon after.

**Comment by ukscone** [comment]
I had some time yesterday to fiddle and I still can't replicate and what I thought might be causing it (kernel version) doesn't seem to be it. I'll have a think but until I can find a way to replicate it anything I do will be guess work. You are all using HDMI monitors?

**Comment by micw** [comment]
@ukscone Sorry for the long delay of my feedback - I did not had access to the pi where I had this problem with.
The command above gives me: 1824x1024
I have a HDMI monitor connected
Kernel is 4.1.19+ (Debian Squeeze)

**Comment by micw** [comment]
After short code review I have a guess:
BYTES=$(expr $FXRES \* $FYRES \* 2)
That's 2 byte per pixel but fbset shows 32 bit (that's 4 byte per pixel):

    # fbset 
    mode "1824x1024"
        geometry 1824 1024 1824 1024 32
        timings 0 0 0 0 0 0 0
        rgba 8/16,8/8,8/0,8/24
    endmode

**Comment by ukscone** [comment]
didn't notice the reply to this but looks like it's been fixed in the pr so closing for now
