### ISSUE TITLE
changing overscan without reboot doesn't affect graphical (dispmanx) apps?

### ISSUE THREAD

**Issue by aubade** [ukscone/set_overscan#7]
I'm using a RasPi to emulate old games, and I've stumbled onto a dilemma that this program appears to be the closest thing to a solution for:

1) When overscan_scale is turned off, dispmanx apps do not respect overscan settings and the edges of the menu GUI get cut off

2) when overscan_scale is turned on, games run in emulators get nasty scaling artifacts

My hope is to be able to use this program to turn off overscan compensation completely when an emulator is launched, ensuring as close to pixel-perfect display as is possible, and to set it back to a sensible value when returning to the menu GUI. 

Unfortunately, it seems like while the text console obeys new overscan settings, dispmanx-using apps including both emulators and the menu program continue to use whatever was set at bootup. Is there anything that this program could do about that? Or could it possibly even toggle the overscan_scale setting during runtime in a way that would affect newly-launched dispmanx programs?

**Comment by ukscone** [comment]
it might be possible but i've not looked at dispmanx at all as nearly all my Pis are used headless (i haven't even used set_overscan myself in over two years & might even be broken). set_overscan talks to the videocore mailboxs https://github.com/raspberrypi/firmware/wiki/Mailbox-property-interface to set the overscan values so if dispmanx is not respecting them there is nothing set_overscan as it is can do about it but it might be possible to tweak some of the values in the other mailboxes to get your desired effect.

**Comment by ukscone** [comment]
doesn't look like it's possible so closing from now but i'll continue investigating
