### ISSUE TITLE
function not found

### ISSUE THREAD

**Issue by ronbanks** [ukscone/set_overscan#9]
I know this is dated and maybe no longer works, but I though I'd give it a shot. I'm getting:
set_overscan.sh: 42: set_overscan.sh: function: not found
when I try to run this. Am I doing something wrong? Does this no longer work? Is there a better way now?

**Comment by ukscone** [comment]
it should work. i just did a quick clone and run and seems to be fine. 
can you try downloading it again just in case there was a glitch and what versions of bash, raspbian are you running?

**Comment by ukscone** [comment]
i've also changed the function def to be more "portable" across shells which might help

**Comment by ronbanks** [comment]
fresh download from here and also tried popcornmix.
I ran make again and is says 'make: 'overscan' is up to date.'
Raspbian GNU/Linux 8 (jessie)
GNU bash, version 4.3.30(1)-release (arm-unknown-linux-gnueabihf)

Am I just missing something?

**Comment by ronbanks** [comment]
can't run make on this version?

**Comment by ukscone** [comment]
the overscan program didn't change so you don't need to rerun make just 
sudo ./set_overscan.sh

**Comment by ronbanks** [comment]
ok, so it does run but when I hit an arrow key or the q key it says './overscan No such file or directory

**Comment by ukscone** [comment]
are you running the script inside the set_overscan directory with all these files in it?



> Makefile  overscan  overscan.c  README.md  set_overscan.sh

**Comment by ronbanks** [comment]
yes,

-rw-r--r-- 1 root root 6392064 Aug  1 12:14 cleared
-rw-rw-r-- 1 pi   pi        64 Aug  1 12:02 Makefile
-rw-rw-r-- 1 pi   pi      3510 Aug  1 12:02 overscan.c
-rw-r--r-- 1 root root 6392064 Aug  1 12:14 rand
-rw-rw-r-- 1 pi   pi      1406 Aug  1 12:02 README.md
-rwxr-xr-x 1 pi   pi      8795 Aug  1 12:02 set_overscan.sh

**Comment by ukscone** [comment]
nope you are missing the executable called overscan

you'll need to type 

> make

and after a few seconds you you'll have a file called overscan and then it SHOULD all work

**Comment by ronbanks** [comment]
hmm, not sure why it didn't make the first time but it did make it this time. The program runs and I'm guessing does what it's supposed to. This probably has nothing to do with the program but I can't get it to fill the screen completely left to right.

**Comment by ukscone** [comment]
the calculations for the screen size are a bit iffy as there are as many edge cases as there are tv models. although it's not really a solution go as far left and right as you can go and guesstimate the size of the black area then subtract that from the left value & add to the right

**Comment by ronbanks** [comment]
actually, it works perfectly, and just what I needed. I wanted my users to be able to plug the pi into whatever display they had and have a tool to do this exact thing without a bunch of reboots, but then that's exactly why you made it. Thanks, works great!

**Comment by ukscone** [comment]
Great, glad it was helpful. I'll close this issue now then
